### ISSUE TITLE
*.pdf in der .gitignore

### ISSUE THREAD

**Issue by pschild** [snehls/latex-vorlage-hsrw#1]
Bin mir gerade nicht sicher, aber ich denke es wäre sinnig, wenn man *.pdf-Dateien auch ignoriert und nicht mit versioniert, oder was meinst du? Jeder, der sich das auscheckt, kann ja eh selber welche generieren ;-)

**Comment by snehls** [comment]
Du hast recht! Ich habe jetzt endlich mal die gitignore angepasst und PDF-Dateien werden ab sofort nicht mehr versioniert! ;)
